Parameters:
  Name:
    Description: The name of the activity.
    Type: String
  Key:
    Description: The key for a key-value pair in a tag entry.
    Type: String
  Value:
    Description: The value for a key-value pair in a tag entry.
    Type: String
Resources:
  StepFunctionActivity:
    Type: AWS::StepFunctions::Activity
    Properties: 
      Name: 
        Ref: Name
      Tags: 
        Key: 
          Ref: Key
        Value: 
          Ref: Value
Outputs:
  Name:
    Description: The name of the activity.
    Value:
      Ref: StepFunctionActivity