Parameters:
  AnalysisId:
    Description: The ID for the analysis that you're creating. This ID displays in the URL of the analysis.
    Type: String
  AwsAccountId:
    Description: The ID of the AWS account where you are creating an analysis.
    Type: String
  Name:
    Description: A descriptive name for the analysis that you're creating. This name displays for the analysis in the Amazon QuickSight console.
    Type: String
  ThemeArn:
    Description: The ARN for the theme to apply to the analysis that you're creating. To see the theme in the Amazon QuickSight console, make sure that you have access to it.
    Type: String
  Message:
    Description: The message associated with the analysis error.
    Type: String
  Type:
    Description: The type of the analysis error.
    Type: String
  DateTimeParametersName:
    Description: A display name for the date-time parameter.
    Type: String
  DateTimeParametersValues:
    Description: The values for the date-time parameter.
    Type: String
  DecimalParametersName:
    Description: A display name for the decimal parameter.
    Type: String
  DecimalParametersValues:
    Description: The values for the decimal parameter.
    Type: String #double
  IntegerParametersName:
    Description: The name of the integer parameter.
    Type: String
  IntegerParametersValues:
    Description: The values for the integer parameter.
    Type: String #double
  StringParametersName:
    Description: A display name for a string parameter.
    Type: String
  StringParametersValues:
    Description: The values of a string parameter.
    Type: String
  Actions:
    Description: The IAM action to grant or revoke permissions on.
    Type: String
  Principal:
    Description: The Amazon Resource Name (ARN) of the principal. 
    Type: String
  Arn:
    Description: The Amazon Resource Name (ARN) of the source template of an analysis.
    Type: String
  DataSetArn:
    Description: Dataset Amazon Resource Name (ARN).
    Type: String
  DataSetPlaceholder:
    Description: Dataset placeholder.
    Type: String
  Key:
    Description: The key name of the tag. 
    Type: String
  Value:
    Description: The value for the tag. You can specify a value that's 1 to 256 characters in length.
    Type: String
Resources:
  QuickSightAnalysis:
    Type: AWS::QuickSight::Analysis
    Properties: 
      AnalysisId: 
        Ref: AnalysisId
      AwsAccountId: 
        Ref: AwsAccountId
      Errors: 
        Message: 
          Ref: Message
        Type: 
          Ref: Type
      Name: 
        Ref: Name
      Parameters: 
        DateTimeParameters: 
          Name: 
            Ref: DateTimeParametersName
          Values: 
            Ref: DateTimeParametersValues
        DecimalParameters: 
          Name: 
            Ref: DecimalParametersName
          Values: 
            Ref: DecimalParametersValues
        IntegerParameters: 
          Name: 
            Ref: IntegerParametersName
          Values: 
            Ref: IntegerParametersValues
        StringParameters: 
          Name: 
            Ref: StringParametersName
          Values: 
            Ref: StringParametersValues
      Permissions: 
        Actions: 
          Ref: Actions
        Principal: 
          Ref: Principal
      SourceEntity: 
        SourceTemplate: 
          Arn: 
            Ref: Arn
          DataSetReferences: 
            DataSetArn: 
              Ref: DataSetArn
            DataSetPlaceholder: 
              Ref: DataSetPlaceholder
      Tags: 
        Key: 
          Ref: Key
        Value: 
          Ref: Value
      ThemeArn: 
        Ref: ThemeArn
Outputs:
  Arn:
    Description: The Amazon Resource Name (ARN) of the source template of an analysis.
    Value:
      Ref: QuickSightAnalysis
  DataSetArn:
    Description: Dataset Amazon Resource Name (ARN).
    Value:
      Ref: QuickSightAnalysis