Parameters:
  NotebookInstanceLifecycleConfigName:
    Description: The name of the lifecycle configuration.
    Type: String
  OnCreateContent:
    Description: A shell script that runs only once, when you create a notebook instance. The shell script must be a base64-encoded string.
    Type: String
  OnStartContent:
    Description: A shell script that runs every time you start a notebook instance, including when you create the notebook instance. The shell script must be a base64-encoded string.
    Type: String
Resources:
  SagemakerNotebookInstanceLifecycleConfig:
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties: 
      NotebookInstanceLifecycleConfigName: 
        Ref: NotebookInstanceLifecycleConfigName
      OnCreate: 
        Content: 
          Ref: OnCreateContent
      OnStart: 
        Content: 
          Ref: OnStartContent