Parameters:
  AwsAccountId:
    Description: The ID of the AWS account where you are creating an analysis.
    Type: String
  DataSetId:
    Description: An ID for the dataset that you want to create. This ID is unique per AWS Region for each AWS account.
    Type: String
  ImportMode:
    Description: Indicates whether you want to import the data into SPICE.
    Type: String
  Name:
    Description: The display name for the dataset.
    Type: String
  Tags:
    Description: Contains a map of the key-value pairs for the resource tag or tags assigned to the dataset.
    Type: String 
  Columns:
    Description: Columns in this hierarchy.
    Type: String 
  CountryCode:
    Description: Country code.
    Type: String 
  GeoSpatialColumnGroupName:
    Description: A display name for the hierarchy.
    Type: String 
  ColumnNames:
    Description: An array of column names.
    Type: String
  Principals:
    Description: An array of Amazon Resource Names (ARNs) for Amazon QuickSight users or groups.
    Type: String 
  Key:
    Description: The folder that contains fields and nested subfolders for your dataset.
    Type: map
  Value:
    Description: The folder that contains fields and nested subfolders for your dataset.
    Type: map
  IngestionWaitTimeInHours:
    Description: The maximum time (in hours) to wait for Ingestion to complete. Default timeout is 36 hours. 
    Type: double
  WaitForSpiceIngestion:
    Description: Wait for SPICE ingestion to finish to mark dataset creation or update as successful. 
    Type: boolean
  Actions:
    Description: The IAM action to grant or revoke permissions on.
    Type: String
  Principal:
    Description: The Amazon Resource Name (ARN) of the principal. 
    Type: String
  Arn:
    Description: he Amazon Resource Name (ARN) of the dataset that contains permissions for RLS.
    Type: double
  FormatVersion:
    Description: The user or group rules associated with the dataset that contains permissions for RLS.
    Type: boolean
  Namespace:
    Description: The namespace associated with the dataset that contains permissions for RLS.
    Type: String
  PermissionPolicy:
    Description: The type of permissions to use when interpreting the permissions for RLS. DENY_ACCESS is included for backward compatibility only.
    Type: String
Resources:
  QuickSightDataSet:
    Type: AWS::QuickSight::DataSet
    Properties: 
      AwsAccountId: 
        Ref: AwsAccountId
      ColumnGroups: 
        GeoSpatialColumnGroup: 
          Columns: 
            Ref: Columns
          CountryCode: 
            Ref: CountryCode
          Name: 
            Ref: GeoSpatialColumnGroupName
      ColumnLevelPermissionRules: 
        ColumnNames: 
          Ref: ColumnNames
        Principals: 
          Ref: Principals
      DataSetId: 
        Ref: DataSetId
      FieldFolders: 
        Key: 
          Ref: Key
        Value: 
          Ref: Value
      ImportMode: 
        Ref: ImportMode
      IngestionWaitPolicy: 
        IngestionWaitTimeInHours: 
          Ref: IngestionWaitTimeInHours
        WaitForSpiceIngestion: 
          Ref: WaitForSpiceIngestion
      LogicalTableMap: 
        Key : Value
      Name: 
        Ref: Name
      Permissions: 
        Actions: 
          Ref: Actions
        Principal: 
          Ref: Principal
      PhysicalTableMap: 
        Key : Value
      RowLevelPermissionDataSet: 
        Arn: 
          Ref:Arn 
        FormatVersion: 
          Ref: FormatVersion
        Namespace: 
          Ref: Namespace
        PermissionPolicy: 
          Ref: PermissionPolicy
      Tags: 
        Ref: Tags
Outputs:
  Arn:
    Description: he Amazon Resource Name (ARN) of the dataset that contains permissions for RLS.
    Value:
      Ref: QuickSightDataSet
  Columns:
    Description: Columns in this hierarchy.
    Value:
      Ref: QuickSightDataSet