Parameters:
  CodeRepositoryName:
    Description: The name of the Git repository.
    Type: String
  GitConfig: 
    Description: Configuration details for the Git repository, including the URL where it is located and the ARN of the AWS Secrets Manager secret that contains the credentials used to access the repository.
    Type: String
  Tags:
    Description: List of tags for Code Repository.
    Type: String
Resources:
  CodeRepo:
    Type: AWS::SageMaker::CodeRepository
    Properties: 
      CodeRepositoryName:
        Ref: CodeRepositoryName
      GitConfig: 
        Ref: GitConfig
      Tags: 
        Ref: Tag
Outputs:
  CodeRepositoryName:
    Description: The name of the Git repository.
    Value:
      Ref: CodeRepo