Resources: 
  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - dms.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: 
            - 'logs:DescribeLogGroups'
            - 'logs:DescribeLogStreams'
            - 'logs:DescribeLogStreams'
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            # - 'ec2:DeleteNetworkInterface'
            # - 'ec2:ModifyNetworkInterfaceAttribute'
          Resource: "*"
      Roles:
      - !Ref RootRole
  
  myReplicationSubnetGroup: 
    Type: "AWS::DMS::ReplicationSubnetGroup"
    Properties: 
      ReplicationSubnetGroupDescription: description
      ReplicationSubnetGroupIdentifier: identifier
      SubnetIds: 
        - subnet-7b5b4112
        - subnet-7b5b4115

  rReplicationInstanceSubnetGroupLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/subnetgroup/${myReplicationSubnetGroup}'
      RetentionInDays: 30