Parameters:
  AppNetworkAccessType:
    Description: Specifies the VPC used for non-EFS traffic. The default value is PublicInternetOnly.
    Type: String
  AppSecurityGroupManagement: 
    Description: The entity that creates and manages the required security groups for inter-app communication in VpcOnly mode.
    Type: String
  AuthMode:
    Description: The mode of authentication that members use to access the Domain.
    Type: String
  ExecutionRole:
    Description: The execution role for the user.
    Type: String
  SecurityGroups:
    Description: The security groups for the Amazon Virtual Private Cloud (VPC) that Studio uses for communication.
    Type: String
  InstanceType:
    Description: The instance type that the image version runs on.
    Type: String
  SageMakerImageArn:
    Description: The ARN of the SageMaker image that the image version belongs to.
    Type: String
  SageMakerImageVersionArn:
    Description: The ARN of the image version created on the instance.
    Type: String
  AppImageConfigName:
    Description: The name of the AppImageConfig.
    Type: String
  ImageName:
    Description: The name of the CustomImage. Must be unique to your account.
    Type: String
  ImageVersionNumber:
    Description: The version number of the CustomImage.
    Type: Integer
  DefaultInstanceType:
    Description: The instance type that the image version runs on.
    Type: String
  DefaultSageMakerImageArn:
    Description: The ARN of the SageMaker image that the image version belongs to.
    Type: String
  DefaultSageMakerImageVersionArn:
    Description: The ARN of the image version created on the instance.
    Type: String
  AccessStatus:
    Description: Indicates whether the current user has access to the RStudioServerPro app.
    Type: String
  UserGroup:
    Description: The level of permissions that the user has within the RStudioServerPro app.
    Type: String
  NotebookOutputOption:
    Description: Whether to include the notebook cell output when sharing the notebook. The default is Disabled.
    Type: String
  S3KmsKeyId:
    Description: When NotebookOutputOption is Allowed, the AWS Key Management Service (KMS) encryption key ID used to encrypt the notebook cell output in the Amazon S3 bucket.
    Type: String
  S3OutputPath:
    Description: When NotebookOutputOption is Allowed, the Amazon S3 bucket used to store the shared notebook snapshots.
    Type: String
  DomainName:
    Description: The domain name.
    Type: String
  SecurityGroupIds:
    Description: The security groups for the Amazon Virtual Private Cloud that the Domain uses for communication between Domain-level apps and user apps.
    Type: String
  DomainExecutionRoleArn:
    Description: cc
    Type: String
  RStudioConnectUrl:
    Description: A URL pointing to an RStudio Connect server.
    Type: String
  RStudioPackageManagerUrl:
    Description: A URL pointing to an RStudio Package Manager server.
    Type: String
  DefaultResourceSpecInstanceType:
    Description: The instance type that the image version runs on.
    Type: String
  DefaultResourceSpecSageMakerImageArn:
    Description: The ARN of the SageMaker image that the image version belongs to.
    Type: String
  DefaultResourceSpecSageMakerImageVersionArn:
    Description: The ARN of the image version created on the instance.
    Type: String
  KmsKeyId:
    Description: SageMaker uses AWS KMS to encrypt the EFS volume attached to the Domain with an AWS managed customer master key (CMK) by default.
    Type: String
  SubnetIds:
    Description: The VPC subnets that Studio uses for communication.
    Type: String
  Tags:
    Description: Tags to associated with the Domain. Each tag consists of a key and an optional value.
    Type: String
  VpcId: 
    Description: The ID of the Amazon Virtual Private Cloud (Amazon VPC) that Studio uses for communication.
    Type: String
Resources:
  SagemakerDomain:
    Type: AWS::SageMaker::Domain
    Properties: 
      AppNetworkAccessType:
        Ref: AppNetworkAccessType 
      AppSecurityGroupManagement:
        Ref: AppSecurityGroupManagement 
      AuthMode:
        Ref: AuthMode 
      DefaultUserSettings: 
        ExecutionRole: 
          Ref: ExecutionRole
        JupyterServerAppSettings: 
          DefaultResourceSpec: 
          InstanceType: 
            Ref: InstanceType
          SageMakerImageArn: 
            Ref: SageMakerImageArn
          SageMakerImageVersionArn: 
            Ref: SageMakerImageVersionArn
        KernelGatewayAppSettings: 
          CustomImages: 
            AppImageConfigName: 
              Ref: AppImageConfigName
            ImageName: 
              Ref: ImageName
            ImageVersionNumber: 
              Ref: ImageVersionNumber
          DefaultResourceSpec: 
            InstanceType: 
              Ref: DefaultInstanceType
            SageMakerImageArn: 
              Ref: DefaultSageMakerImageArn
            SageMakerImageVersionArn: 
              Ref: DefaultSageMakerImageVersionArn
        RStudioServerProAppSettings: 
          AccessStatus: 
            Ref: AccessStatus
          UserGroup: 
            Ref: UserGroup
        SecurityGroups: 
          Ref: SecurityGroups
        SharingSettings: 
          NotebookOutputOption: 
            Ref: NotebookOutputOption
          S3KmsKeyId: 
            Ref: S3KmsKeyId
          S3OutputPath: 
            Ref: S3OutputPath
      DomainName: 
        Ref: DomainName
      DomainSettings: 
        RStudioServerProDomainSettings: 
          DefaultResourceSpec: 
            InstanceType: 
              Ref: DefaultResourceSpecInstanceType
            SageMakerImageArn: 
              Ref: DefaultResourceSpecSageMakerImageArn
            SageMakerImageVersionArn: 
              Ref: DefaultResourceSpecSageMakerImageVersionArn
          DomainExecutionRoleArn: 
            Ref: DomainExecutionRoleArn
          RStudioConnectUrl: 
            Ref: RStudioConnectUrl
          RStudioPackageManagerUrl: 
            Ref: RStudioPackageManagerUrl
        SecurityGroupIds: 
          Ref: SecurityGroupIds
      KmsKeyId:
        Ref: KmsKeyId
      SubnetIds: 
        Ref: SubnetIds
      Tags: 
        Ref: Tags 
      VpcId: 
        Ref: VpcId 
Outputs:
  DomainExecutionRoleArn:
    Description: The ARN of the execution role for the RStudioServerPro Domain-level app.
    Value:
      Ref: SagemakerDomain