Parameters:
  RoleArn:
    Description: The Amazon Resource Name (ARN) of an IAM role that Amazon SageMaker can assume to perform tasks on your behalf.
    Type: String
  EndpointName:
    Description: The name of the endpoint using the monitoring schedule.
    Type: String
  FailureReason:
    Description: Contains the reason a monitoring job failed, if it failed.
    Type: String
  MonitoringScheduleName:
    Description: The name of the monitoring schedule.
    Type: String
  MonitoringScheduleStatus:
    Description: The status of the monitoring schedule.
    Type: String
  CreationTime:
    Description: The time at which the monitoring job was created.
    Type: String
  EndpointName:
    Description: The name of the endpoint used to run the monitoring job.
    Type: String
  FailureReason:
    Description: Contains the reason a monitoring job failed, if it failed.
    Type: String
  LastModifiedTime:
    Description: A timestamp that indicates the last time the monitoring job was modified.
    Type: String
  MonitoringExecutionStatus:
    Description: The status of the monitoring job.
    Type: String
  MonitoringScheduleName:
    Description: The name of the monitoring schedule.
    Type: String
  ProcessingJobArn:
    Description: The Amazon Resource Name (ARN) of the monitoring job.
    Type: String
  ScheduledTime:
    Description: The time the monitoring job was scheduled.
    Type: String
  MonitoringJobDefinitionName:
    Description: The name of the monitoring job definition to schedule.
    Type: String
  MonitoringType:
    Description: The type of the monitoring job definition to schedule.
    Type: String
  key:
    Description: Sets the environment variables in the container that the monitoring job runs.
    Type: map
  value:
    Description: Sets the environment variables in the container that the monitoring job runs.
    Type: map
  EnableInterContainerTrafficEncryption:
    Description: Whether to encrypt all communications between distributed processing jobs. 
    Type: boolean
  EnableNetworkIsolation:
    Description: Whether to allow inbound and outbound network calls to and from the containers used for the processing job.
    Type: boolean
  SecurityGroupIds:
    Description: The VPC security group IDs, in the form sg-xxxxxxxx. Specify the security groups for the VPC that is specified in the Subnets field.
    Type: String
  Subnets:
    Description: The ID of the subnets in the VPC to which you want to connect your training job or model.
    Type: String
  MaxRuntimeInSeconds:
    Description: The maximum length of time, in seconds, that a training or compilation job can run.
    Type: integer
  ScheduleExpression:
    Description: A cron expression that describes details about the monitoring schedule.
    Type: String
  ConstraintsResourceS3Uri:
    Description: The Amazon S3 URI for the constraints resource.
    Type: String
  StatisticsResourceS3Uri:
    Description: The S3 URI for the statistics resource.
    Type: String
  ContainerArguments:
    Description: An array of arguments for the container used to run the monitoring job.
    Type: String
  ContainerEntrypoint:
    Description: Specifies the entrypoint for a container used to run the monitoring job.
    Type: String
  ImageUri:
    Description: The container image to be run by the monitoring job.
    Type: String
  PostAnalyticsProcessorSourceUri:
    Description: An Amazon S3 URI to a script that is called after analysis has been performed. Applicable only for the built-in (first party) containers.
    Type: String
  RecordPreprocessorSourceUri:
    Description: An Amazon S3 URI to a script that is called per row prior to running analysis.
    Type: String
  InstanceType:
    Description: Not currently supported by AWS CloudFormation.
    Type: String
  VolumeKmsKeyId:
    Description: Not currently supported by AWS CloudFormation.
    Type: String
  InstanceCount:
    Description: Not currently supported by AWS CloudFormation.
    Type: integer
  VolumeSizeInGB:
    Description: Not currently supported by AWS CloudFormation.
    Type: integer
  Tags:
    Description: An array of key-value pairs to apply to this resource.
    Type: String
  EndpointName:
    Description: An endpoint in customer's account which has enabled DataCaptureConfig enabled.
    Type: String
  LocalPath:
    Description: Path to the filesystem where the endpoint data is available to the container.
    Type: String
  S3DataDistributionType:
    Description: Whether input data distributed in Amazon S3 is fully replicated or sharded by an S3 key. 
    Type: String
  S3InputMode:
    Description: Whether the Pipe or File is used as the input mode for transferring data for the monitoring job. 
    Type: String  
  MonitoringOutputConfigKmsKeyId:
    Description: The AWS Key Management Service (AWS KMS) key that Amazon SageMaker uses to encrypt the model artifacts at rest using Amazon S3 server-side encryption.
    Type: String
  S3OutputLocalPath:
    Description: The local path to the Amazon S3 storage location where Amazon SageMaker saves the results of a monitoring job.
    Type: String
  S3OutputS3UploadMode:
    Description: Whether to upload the results of the monitoring job continuously or after the job completes.
    Type: String
  S3OutputS3Uri:
    Description: A URI that identifies the Amazon S3 storage location where Amazon SageMaker saves the results of a monitoring job.
    Type: String
Resources:
  SagemakerMonitoringSchedule:
    Type: AWS::SageMaker::MonitoringSchedule
    Properties: 
      EndpointName: 
        Ref: EndpointName
      FailureReason: 
        Ref: FailureReason
      LastMonitoringExecutionSummary: 
        CreationTime: 
          Ref: CreationTime
        EndpointName: 
          Ref: EndpointName
        FailureReason: 
          Ref: FailureReason
        LastModifiedTime: 
          Ref: LastModifiedTime
        MonitoringExecutionStatus: 
          Ref: MonitoringExecutionStatus
        MonitoringScheduleName: 
          Ref: MonitoringScheduleName
        ProcessingJobArn: 
          Ref: ProcessingJobArn
        ScheduledTime: 
          Ref: ScheduledTime
      MonitoringScheduleConfig: 
        MonitoringJobDefinition: 
          BaselineConfig: 
            ConstraintsResource: 
              S3Uri: 
                Ref: ConstraintsResourceS3Uri
            StatisticsResource: 
              S3Uri: 
                Ref: StatisticsResourceS3Uri
          Environment: 
            key: 
              Ref: key
            value:
              Ref: value
          MonitoringAppSpecification: 
            ContainerArguments: 
              Ref: ContainerArguments
            ContainerEntrypoint: 
              Ref: ContainerEntrypoint
            ImageUri: 
              Ref: ImageUri
            PostAnalyticsProcessorSourceUri: 
              Ref: PostAnalyticsProcessorSourceUri
            RecordPreprocessorSourceUri: 
              Ref: RecordPreprocessorSourceUri
          MonitoringInputs: 
            EndpointInput: 
              EndpointName: 
                Ref: EndpointName
              LocalPath: 
                Ref: LocalPath
              S3DataDistributionType: 
                Ref: S3DataDistributionType
              S3InputMode: 
                Ref: S3InputMode
          MonitoringOutputConfig: 
            KmsKeyId: 
              Ref: MonitoringOutputConfigKmsKeyId
            MonitoringOutputs: 
              S3Output: 
                LocalPath: 
                  Ref: S3OutputLocalPath
                S3UploadMode: 
                  Ref: S3OutputS3UploadMode
                S3Uri: 
                  Ref: S3OutputS3Uri
          MonitoringResources: 
            ClusterConfig: 
              InstanceCount: 
                Ref: InstanceCount
              InstanceType: 
                Ref: InstanceType
              VolumeKmsKeyId: 
                Ref: VolumeKmsKeyId
              VolumeSizeInGB: 
                Ref: VolumeSizeInGB
          NetworkConfig: 
            EnableInterContainerTrafficEncryption:
              Ref: EnableInterContainerTrafficEncryption
            EnableNetworkIsolation:
              Ref: EnableNetworkIsolation
            VpcConfig: 
              SecurityGroupIds: 
                Ref: SecurityGroupIds
              Subnets: 
                Ref: Subnets
          RoleArn: 
            Ref: RoleArn
          StoppingCondition: 
            MaxRuntimeInSeconds: 
              Ref: MaxRuntimeInSeconds 
        MonitoringJobDefinitionName: 
          Ref: MonitoringJobDefinitionName
        MonitoringType: 
          Ref: MonitoringType
        ScheduleConfig: 
          ScheduleExpression: 
            Ref: ScheduleExpression
      MonitoringScheduleName: 
        Ref: MonitoringScheduleName
      MonitoringScheduleStatus: 
        Ref: MonitoringScheduleStatus
      Tags: 
        Ref: Tags
Outputs:
  LastModifiedTime:
    Description: A timestamp that indicates the last time the monitoring job was modified.
    Value:
      Ref: SagemakerMonitoringSchedule
  ScheduledTime:
    Description: The time the monitoring job was scheduled.
    Value:
      Ref: SagemakerMonitoringSchedule
  CreationTime:
    Description: The time at which the monitoring job was created.
    Value:
      Ref: SagemakerMonitoringSchedule
  RoleArn:
    Description: The Amazon Resource Name (ARN) of an IAM role that Amazon SageMaker can assume to perform tasks on your behalf.
    Value:
      Ref: SagemakerMonitoringSchedule