Parameters:
  ContainerArguments:
    Description: The arguments to send to the container that the monitoring job runs.
    Type: String
  ContainerEntrypoint: 
    Description: The entrypoint for a container used to run a monitoring job.
    Type: String
  key: 
    Description: Sets the environment variables in the container that the monitoring job runs.
    Type: String
  value: 
    Description: Sets the environment variables in the container that the monitoring job runs.
    Type: String
  ImageUri:
    Description: The container image that the data quality monitoring job runs.
    Type: String
  PostAnalyticsProcessorSourceUri:
    Description: An Amazon S3 URI to a script that is called after analysis has been performed. Applicable only for the built-in (first party) containers.
    Type: String
  RecordPreprocessorSourceUri:
    Description: An Amazon S3 URI to a script that is called per row prior to running analysis. 
    Type: String
  BaseliningJobName:
    Description: The name of the job that performs baselining for the data quality monitoring job.
    Type: String
  ConstraintsResourceS3Uri:
    Description: The Amazon S3 URI for the constraints resource.
    Type: String
  StatisticsResourceS3Uri:
    Description: The Amazon S3 URI for the statistics resource.
    Type: String
  EndpointName:
    Description: An endpoint in customer's account which has enabled DataCaptureConfig enabled.
    Type: String
  EndpointInputLocalPath:
    Description: Path to the filesystem where the endpoint data is available to the container.
    Type: String
  S3DataDistributionType:
    Description: Whether input data distributed in Amazon S3 is fully replicated or sharded by an S3 key.
    Type: String
  S3InputMode:
    Description: Whether the Pipe or File is used as the input mode for transferring data for the monitoring job. 
    Type: String
  KmsKeyId:
    Description: The AWS Key Management Service (AWS KMS) key that Amazon SageMaker uses to encrypt the model artifacts at rest using Amazon S3 server-side encryption.
    Type: String
  MonitoringOutputsLocalPath:
    Description: The local path to the Amazon S3 storage location where Amazon SageMaker saves the results of a monitoring job. 
    Type: String
  S3UploadMode:
    Description: Whether to upload the results of the monitoring job continuously or after the job completes.
    Type: String
  MonitoringOutputsS3Uri:
    Description: A URI that identifies the Amazon S3 storage location where Amazon SageMaker saves the results of a monitoring job.
    Type: String
  JobDefinitionName:
    Description: The name for the monitoring job definition.
    Type: String
  InstanceCount:
    Description: The number of ML compute instances to use in the model monitoring job. 
    Type: Integer
  InstanceType:
    Description: Type of Instance
    Type: String
  VolumeKmsKeyId:
    Description: The AWS Key Management Service (AWS KMS) key that Amazon SageMaker uses to encrypt data on the storage volume attached to the ML compute instance(s) that run the model monitoring job.
    Type: String
  VolumeSizeInGB:
    Description: The size of the ML storage volume, in gigabytes, that you want to provision. You must specify sufficient ML storage for your scenario.
    Type: String
  SecurityGroupIds:
    Description: The VPC security group IDs, in the form sg-xxxxxxxx. Specify the security groups for the VPC that is specified in the Subnets field.
    Type: String
  Subnets:
    Description: The ID of the subnets in the VPC to which you want to connect your training job or model. 
    Type: String
  RoleArn:
    Description: The Amazon Resource Name (ARN) of an IAM role that Amazon SageMaker can assume to perform tasks on your behalf.
    Type: String
  MaxRuntimeInSeconds:
    Description: The maximum length of time, in seconds, that a training or compilation job can run.
    Type: Integer
  EnableInterContainerTrafficEncryption:
    Description: Whether to encrypt all communications between distributed processing jobs. Choose True to encrypt communications. Encryption provides greater security for distributed processing jobs, but the processing might take longer.
    Type: Boolean
  EnableNetworkIsolation:
    Description: Whether to allow inbound and outbound network calls to and from the containers used for the processing job.
    Type: Boolean
  Tags:
    Description: An array of key-value pairs to apply to this resource.
    Type: String
Resources:
  DataQualityJobDef:
    Type: AWS::SageMaker::DataQualityJobDefinition
    Properties: 
      DataQualityAppSpecification: 
        ContainerArguments: 
          Ref: ContainerArguments
        ContainerEntrypoint: 
          Ref: ContainerEntrypoint
        Environment: 
          Name: 
            Ref: key
          Value: 
            Ref: value
        ImageUri: 
          Ref: ImageUri
        PostAnalyticsProcessorSourceUri: 
          Ref: PostAnalyticsProcessorSourceUri
        RecordPreprocessorSourceUri: 
          Ref: RecordPreprocessorSourceUri
      DataQualityBaselineConfig: 
        BaseliningJobName: 
          Ref: BaseliningJobName
        ConstraintsResource: 
          S3Uri: 
            Ref: ConstraintsResourceS3Uri
        StatisticsResource: 
          S3Uri: 
            Ref: StatisticsResourceS3Uri
      DataQualityJobInput: 
        EndpointInput: 
          EndpointName: 
            Ref: EndpointName
          LocalPath: 
            Ref: EndpointInputLocalPath
          S3DataDistributionType: 
            Ref: S3DataDistributionType
          S3InputMode: 
            Ref: S3InputMode
      DataQualityJobOutputConfig: 
        KmsKeyId: 
          Ref: KmsKeyId
        MonitoringOutputs: 
          S3Output: 
            LocalPath: 
              Ref: MonitoringOutputsLocalPath
            S3UploadMode: 
              Ref: S3UploadMode
            S3Uri:
              Ref: MonitoringOutputsS3Uri 
      JobDefinitionName:
        Ref: JobDefinitionName 
      JobResources: 
        ClusterConfig: 
          InstanceCount: 
            Ref: InstanceCount
          InstanceType:
            Ref: InstanceType 
          VolumeKmsKeyId:
            Ref: VolumeKmsKeyId 
          VolumeSizeInGB: 
            Ref: VolumeSizeInGB
      NetworkConfig: 
        EnableInterContainerTrafficEncryption: 
          Ref: EnableInterContainerTrafficEncryption
        EnableNetworkIsolation: 
          Ref: EnableNetworkIsolation
        VpcConfig: 
          SecurityGroupIds: 
            Ref: SecurityGroupIds
          Subnets: 
            Ref: Subnets
      RoleArn: 
        Ref: RoleArn
      StoppingCondition: 
        MaxRuntimeInSeconds: 
          Ref: MaxRuntimeInSeconds
      Tags: 
        Ref: Tags
Outputs:
  RoleArn:
    Description: The Amazon Resource Name (ARN) of an IAM role that Amazon SageMaker can assume to perform tasks on your behalf.
    Value:
      Ref: RoleArn